channels:
  - cadquery
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - pip
  - cadquery=master
  - pip:
    - git+https://github.com/gumyr/cq_warehouse.git#egg=cq_warehouse
    - git+https://github.com/gumyr/build123d
