name: cadquery

channels:
  - cadquery
  - conda-forge
  - defaults

dependencies:
  - python=3.9
  - cadquery=master
  - cq-editor=master
  - pip
  - pip:
    - git+https://github.com/gumyr/cq_warehouse.git#egg=cq_warehouse
